api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    formats:
        jsonapi:
            mime_types: ['application/vnd.api+json']
        json:
            mime_types: ['application/json']
    enable_swagger_ui: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            client_enabled: true
            enabled_parameter_name: page
