vich_uploader:
    db_driver: orm

    mappings:
        file:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
            directory_namer: my.directory_namer.product
